# Generated by Django 4.2.23 on 2025-09-10 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_dish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='gallery/')),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='dishcategory',
            options={'ordering': ['position']},
        ),
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dishes', to='main.dishcategory'),
        ),
    ]
