# Generated by Django 4.2.23 on 2025-09-26 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: 999999999', regex='^[0-9]{9}$')]),
        ),
    ]
