# Generated by Django 4.2.23 on 2025-10-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_reservation_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('photo', models.ImageField(upload_to='chef/')),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
    ]
